version: '3.8'

services:
  # 1. O nosso Banco de Dados (Postgres)
  db:
    image: postgres:15-alpine
    container_name: natalfy-postgres
    restart: always
    environment:
      POSTGRES_DB: natalfy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432" # Expõe a porta para você poder olhar o banco no seu DBeaver/PgAdmin
    volumes:
      - postgres_data:/var/lib/postgresql/data # Garante que os dados não somem se o container desligar

  # 2. A nossa API (Spring Boot)
  api:
    build: . # Manda o Docker ler o Dockerfile que criamos
    container_name: natalfy-api
    ports:
      - "8080:8080" # A porta do seu Swagger e do .http
    environment:
      # O pulo do gato: Sobrescrevemos o application.yml para a API procurar o banco no container 'db'
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/natalfy_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db # Avisa que a API só pode ligar DEPOIS que o banco estiver pronto

volumes:
  postgres_data: