server:
  port: 8081

spring:
  application:
    name: natalfy

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/natalfy_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.3

app:
  jwt:
    secret: ${JWT_SECRET:SUA_CHAVE_SECRETA_SUPER_SEGURA_E_LONGA_AQUI_12345}
    expiration-ms: 86400000

logging:
  level:
    com.natalfy: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: TRACE