name: CI Natalfy API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: natalfy
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Java 21 (Azul Zulu)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven

      - name: Dar permissão de execução para o Maven Wrapper
        run: chmod +x mvnw

      - name: Rodar todos os Testes Automatizados (com Banco Real)
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SPRING_DATASOURCE_URL: jdbc:postgresql://127.0.0.1:5432/natalfy
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: root
          SPRING_DATA_REDIS_HOST: 127.0.0.1
          SPRING_FLYWAY_CLEAN_DISABLED: false        # permite limpar
          SPRING_FLYWAY_CLEAN_ON_VALIDATION_ERROR: true  # limpa e recria se der erro
        run: ./mvnw clean verify -Dsurefire.useFile=false -e